feat: added ECR Public Registry support
arjraman/amazon-ecr-login pull request #1
Opened 2022-06-09 19:34 UTC by arjraman

*Issue #, if available:*

*Description of changes:*
Added ECR Public support

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-13 00:23 UTC, monirul requested changes
Added few comments. Please let me know if you have any questions.
- Monirul.

2022-06-13 00:23 UTC, monirul commented on README.md
> +This action requires the following minimum set of permissions to login to ECR:
Maybe we can also mention how to set the permission here first. That will guide the customer to the right direction. Otherwise they might end up searching how to set the permission and it might degrade the customer experience.

2022-06-13 00:23 UTC, monirul commented on dist/index.js
> +    customUserAgent: 'amazon-ecr-login-for-github-actions'
Lets create a global const `EcrLoginGitHubActionUserAgent` instead of hard coded string.

2022-06-13 00:23 UTC, monirul commented on dist/index.js
> +    customUserAgent: 'amazon-ecr-login-for-github-actions'
Same. reuse the const here.

2022-06-13 00:23 UTC, monirul commented on dist/index.js
> +  if (!authTokenResponse || !Array.isArray(authTokenResponse.authorizationData) || !authTokenResponse.authorizationData.length) {
Can we provide more details of what went wrong. Does auth response provide any details if there is any error?

2022-06-13 00:23 UTC, monirul commented on dist/index.js
> +  if (!authTokenResponse || !authTokenResponse.authorizationData || Object.keys(authTokenResponse.authorizationData).length === 0) {
Same here.

2022-06-13 00:23 UTC, monirul commented on dist/index.js
> +        proxyEndpoint: 'public.ecr.aws'
Lets create global const instead of hard coded string here.

2022-06-13 00:23 UTC, monirul commented on dist/index.js
> +  const registryType = core.getInput('registry-type', { required: false }).toLowerCase() || 'private';
Same here. global const? e.g. `RegistryTypeEcrPrivate`, `RegistryTypeEcrPublic`

2022-06-13 00:23 UTC, monirul commented on dist/index.js
> +    if (registryType !== 'private' && registryType !== 'public') {
Same here. Replace string with global const? e.g. `RegistryTypeEcrPrivate`, `RegistryTypeEcrPublic`

2022-06-13 00:23 UTC, monirul commented on dist/index.js
> +    if (registryType === 'private' && registries) {
same here.

2022-06-13 00:23 UTC, monirul commented on index.js
>        const registryUri = proxyEndpoint.replace(/^https?:\/\//,'');
Encapsulate in a different function since same code is reused in an other place.

2022-06-13 00:23 UTC, monirul commented on index.js
> +    customUserAgent: 'amazon-ecr-login-for-github-actions'
see the comment on dist/index.js

2022-06-13 00:23 UTC, monirul commented on index.js
> +  if (!authTokenResponse || !Array.isArray(authTokenResponse.authorizationData) || !authTokenResponse.authorizationData.length) {
see the comment on dist/index.js

2022-06-13 00:23 UTC, monirul commented on index.js
> +    customUserAgent: 'amazon-ecr-login-for-github-actions'
see the comment on dist/index.js

2022-06-13 00:23 UTC, monirul commented on index.js
> +  if (!authTokenResponse || !authTokenResponse.authorizationData || Object.keys(authTokenResponse.authorizationData).length === 0) {
see the comment on dist/index.js

2022-06-13 00:23 UTC, monirul commented on index.js
> +        proxyEndpoint: 'public.ecr.aws'
see the comment on dist/index.js

2022-06-13 00:23 UTC, monirul commented on index.js
> +    if (registryType !== 'private' && registryType !== 'public') {
see the comment on dist/index.js

2022-06-13 00:23 UTC, monirul commented on index.js
> +  const registryType = core.getInput('registry-type', { required: false }).toLowerCase() || 'private';
see the comment on dist/index.js

2022-06-15 22:18 UTC, monirul reviewed
Good work @arjraman. Added few more minor changes.

2022-06-15 22:18 UTC, monirul commented on index.js
> +  const authTokenResponse = await ecr.getAuthorizationToken(authTokenRequest).promise();
We can mimic the error by providing wrong credential to mimic authentication issue? Also, what happens when user does not have any permission to login to ecr private/public repo?

2022-06-15 22:18 UTC, monirul commented on index.js
> +  const authTokenResponse = await ecrPublic.getAuthorizationToken(authTokenRequest).promise();
same here.

2022-06-15 22:18 UTC, monirul commented on index.js
> +    if (registryType !== REGISTRY_TYPE_OPTIONS.private && registryType !== REGISTRY_TYPE_OPTIONS.public) {
Rename this variable `REGISTRY_TYPE_OPTIONS` to `REGISTRY_TYPES`.

2022-06-15 22:18 UTC, monirul commented on index.js
> +const REGISTRY_TYPE_OPTIONS = {
Change it to?
```js
const REGISTRY_TYPES = {
  Private: 'private',
  Public: 'public'
};
```

2022-06-15 22:42 UTC, arjraman commented on index.js
> +  const authTokenResponse = await ecr.getAuthorizationToken(authTokenRequest).promise();
Yes they can, it's shown in the unit test cases. If there is an error during the getAuthorizationToken call itself, the call will throw an error and it will be caught. The errors I threw there are for when the call is successful but the data received is invalid.

2022-06-15 23:47 UTC, monirul approved these changes
Changes looks good. As discussed offline, we might need to add troubleshooting section for common errors such as misconfiguration or authentication error.

2022-06-16 00:27 UTC, merged